### ISSUE TITLE
fix: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports"

### ISSUE THREAD

**Issue by mmrakt** [mmrakt/chat-gpt-clone#12]
https://github.com/vercel/next.js/issues/49169

**Comment by mmrakt** [comment]
13.5.2にupgradeすると解消した。
https://github.com/vercel/next.js/issues/49169#issuecomment-1730947230

**Comment by nisithaD** [comment]
Facing same issue..Any solution?
